# 调试信息配置

include(${CMAKE_CURRENT_SOURCE_DIR}/cmake/CheckCXXCompilerFlagAndEnableIt.cmake)

if(LIBRAW_ENABLE_DEBUG_INFO)
  if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
    CHECK_CXX_COMPILER_FLAG_AND_ENABLE_IT(-g3)
  elseif(CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
    CHECK_CXX_COMPILER_FLAG_AND_ENABLE_IT(-g3)
  elseif(CMAKE_CXX_COMPILER_ID STREQUAL "AppleClang")
    CHECK_CXX_COMPILER_FLAG_AND_ENABLE_IT(-g3)
  elseif(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
    CHECK_CXX_COMPILER_FLAG_AND_ENABLE_IT(/Zi)
  endif()
endif()
